### ISSUE TITLE
Comentário Aula 5.

### ISSUE THREAD

**Issue by vntiinfante** [cesinhalius/Vnt-school#1]
Note que o código não corresponde aos comentários!
Cuidado com copy-and-paste... hehe

Isso aconteceu nas linhas: 25, 30, 35, 40 e 45.

Por exemplo,
https://github.com/cesinhalius/Vnt-school/blob/9315ed4ca14d7d09a25d76221e825722e2167ee5/02_Java/Aula5/Exercicio2/src/exercicio2/Exercicio2.java#L25

**Comment by cesinhadev** [comment]
arrumei as validação
