### ISSUE TITLE
Comentário Aula 10 exercício 05

### ISSUE THREAD

**Issue by vntiinfante** [cesinhalius/Vnt-school#10]
Atenção com a lógica.
Note que toda vez que uma opção inválida for informada será contabilizado como um cliente.

https://github.com/cesinhalius/Vnt-school/blob/fc7d5311b434190ba713b3fc6a5cbfe9f80553ee/02_Java/exercicios/ListaExercicio7/Exercicio5/src/exercicio5/Exercicio5.java#L46

**Comment by cesinhadev** [comment]
adicionei a quantidade de cliente em cada opção
