### ISSUE TITLE
Comentário aula10 exercício 06

### ISSUE THREAD

**Issue by vntiinfante** [cesinhalius/Vnt-school#11]
Ficaria melhor se o cabeçalho fosse mostrado uma única vez.

https://github.com/cesinhalius/Vnt-school/blob/fc7d5311b434190ba713b3fc6a5cbfe9f80553ee/02_Java/exercicios/ListaExercicio7/Exercicio6/src/exercicio6/Exercicio6.java#L27

**Comment by cesinhadev** [comment]
Adicionei esse comando antes do comando de repetição
