### ISSUE TITLE
Comentário Aula 08, exercício 02.

### ISSUE THREAD

**Issue by vntiinfante** [cesinhalius/Vnt-school#2]
Se entrar com o número zero, o programa imprime que zero é negativo.

https://github.com/cesinhalius/Vnt-school/blob/9315ed4ca14d7d09a25d76221e825722e2167ee5/02_Java/exercicios/ListaExercicio6/Exercicio2/src/exercicio2/Exercicio2.java#L25

**Comment by cesinhadev** [comment]
ja fiz a mudança para validar o zero
